FROM maven:3.6.3-openjdk-11-slim

RUN apt-get update \
    && apt-get install -y \
        netcat-openbsd \
        git \
        python3 \
        python3-pip \
        python3-setuptools \
        jq \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

CMD ["/usr/src/app/entry.sh"]
